### ISSUE TITLE
Plotting works randomly 

### ISSUE THREAD

**Issue by Balinus** [johnmyleswhite/Vega.jl#146] opened 2017-01-19 14:26 UTC
Hello, using the example for the piechart, I can recreate the example but only 1 time (sometimes 2). After that, most calls to make a figure shows a blank white window. Then, sometimes it work, then it doesn't. Hence, it looks like stability issue. Tried with other example from the documentation and I have the same problem.

As far as I know, I've installed everything and all packages are up-to-date (usually tagged version). I'm using master for Vega.

Code examples:

```
using Vega

fruit = ["peaches", "plums", "blueberries", "strawberries", "bananas"]
bushels = [100, 32, 180, 46, 21]

piechart(x = fruit, y = bushels)
```

```
using Vega, KernelDensity, Distributions

x = rand(Beta(3.0, 2.0), 10)
k = kde(x)

areaplot(x = k.x, y = k.density)
```

```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

```
julia> Pkg.status("Vega")
 - Vega                          0.6.8+             master
```
I can provide more info, just ask.

**Comment by randyzwitch** [comment] 2017-01-20 14:27
Thanks for reporting. I confirmed this with both Jupyter Notebook and from the REPL, and it happens in both locations. Hopefully it's not a big deal to fix.

**Comment by randyzwitch** [comment] 2017-01-23 00:57
If you absolutely need to plot something before waiting for the actual fix, plotting works at commit 55dbe774b0d6f787d1485ac44f33f5da8c704eac. So you can rollback the Vega.jl repo to that point, which removes Blink integration (running code from the REPL will open a browser; Jupyter Notebooks seem to have an unrelated error due to Patchwork.jl).

You can do the following to checkout this specific commit:

cd .julia/v0.5/Vega
git checkout 55dbe774b0d6f787d1485ac44f33f5da8c704eac .

Then, open julia, and a using("Vega") will cause a recompilation and hopefully fixes the error.

**Comment by Balinus** [comment] 2017-01-23 14:33
Thanks for the temp solution. However, I use the package on a cluster which has visual capabilities but no browser (in fact, it has, but Firefox is really slow).

**Comment by randyzwitch** [comment] 2017-01-23 14:35
In that case, you won't be able to use Vega at all, as it is just a wrapper around a JavaScript library. While it is possible to use node.js and Cairo with Vega to generate PNG files, this functionality isn't part of Vega.jl

**Comment by Balinus** [comment] 2017-01-23 14:57
Oh, thanks. I thought that there was some sort of functionality to generate PNG files programmatically.

**Comment by randyzwitch** [comment] 2017-01-23 15:56
That's vaguely #93, I just haven't had the time to implement it. Unfortunately, this package never really took off, so I'm usually the sole developer trying to push new functionality forward.

**Comment by Balinus** [comment] 2017-01-23 16:10
ok, so someday, there might be a Headless mode?

**Comment by randyzwitch** [comment] 2017-04-11 02:03
Closing this...until #148 happens and I learn what is possible from the new JS library, won't even know if this is possible or not. I will keep it in mind certainly

**Closed by randyzwitch** 2017-04-11 02:03 UTC
